name: Deploy to GitHub Pages

on:
  workflow_dispatch: # pozwala na ręczne uruchamianie workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build project
      run: dotnet publish -c Release -o build

    - name: Prepare GitHub Pages folder
      run: |
        mkdir -p docs
        cp -r build/wwwroot/* docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
